name: 编译

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: 安装 Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Rust 缓存
      uses: Swatinem/rust-cache@v2.7.3
    - name: 编译
      run: |
        cd kondo && cargo build --release
        cd kondo-ui && cargo build --release
    - name: 上传文件
      uses: actions/upload-artifact@v4
      with:
         name: kondo
         path: |
           kondo\target\release\kondo.exe
           kondo-ui\target\release\kondo-ui.exe
    
